name: Setup Ruby
description: Checkout code, restore the gems cache and install dependencies

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

    - name: Cache gems
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
      with:
        path: vendor/bundle
        key: gems-${{ runner.os }}-${{ hashFiles('Gemfile.lock') }}
        restore-keys: |
          gems-${{ runner.os }}-

    - name: Install dependencies
      shell: bash
      run: bundle install --quiet
